{
  "openapi": "3.0.0",
  "info": {
    "description": "A public and stable API for interacting with axiom services",
    "title": "Axiom",
    "termsOfService": "http://axiom.co/terms",
    "contact": {
      "name": "Axiom support team",
      "url": "https://axiom.co",
      "email": "hello@axiom.co"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "2.0.0"
  },
  "servers": [
    {
      "url": "https://api.axiom.co/v2/"
    }
  ],
  "paths": {
    "/annotations": {
      "get": {
        "security": [
          {
            "Auth": [
              "annotations|read"
            ]
          }
        ],
        "description": "Get annotations",
        "tags": [
          "annotations"
        ],
        "operationId": "getAnnotations"
      },
      "post": {
        "security": [
          {
            "Auth": [
              "annotations|create"
            ]
          }
        ],
        "description": "Create annotation",
        "tags": [
          "annotations"
        ],
        "operationId": "createAnnotation"
      }
    },
    "/annotations/{id}": {
      "get": {
        "security": [
          {
            "Auth": [
              "annotations|read"
            ]
          }
        ],
        "description": "Get annotation by ID",
        "tags": [
          "annotations"
        ],
        "operationId": "getAnnotation"
      },
      "put": {
        "security": [
          {
            "Auth": [
              "annotations|update"
            ]
          }
        ],
        "description": "Update annotation",
        "tags": [
          "annotations"
        ],
        "operationId": "updateAnnotation"
      },
      "delete": {
        "security": [
          {
            "Auth": [
              "annotations|delete"
            ]
          }
        ],
        "description": "Delete annotation",
        "tags": [
          "annotations"
        ],
        "operationId": "deleteAnnotation"
      }
    },
    "/slack/auth": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Authenticate the user",
        "operationId": "handleSlackAuth",
        "security": [
          {
            "Auth": []
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/slack/auth/callback": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Handle OAuth callback from Slack",
        "operationId": "handleOAuthCallback",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/axiomLogin/callback": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Authenticate the user against Axiom",
        "operationId": "handleAxiomLogin",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/events": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Post Slack events",
        "operationId": "postSlackEvent",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/handleSlashCommand": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Redirect user to Slack for authentication",
        "operationId": "handleSlashCommand",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/interactiveEndpoint": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Post Slack interactive endpoint",
        "operationId": "postSlackInteractiveEndpoint",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/tokens": {
      "get": {
        "security": [
          {
            "Auth": [
              "apiTokens|read"
            ]
          }
        ],
        "description": "Get API tokens",
        "tags": [
          "tokens"
        ],
        "operationId": "getAPITokens"
      },
      "post": {
        "security": [
          {
            "Auth": [
              "apiTokens|create"
            ]
          }
        ],
        "description": "Create API token",
        "tags": [
          "tokens"
        ],
        "operationId": "createAPIToken",
        "x-axiom-not-suspended": true
      }
    },
    "/tokens/{id}": {
      "get": {
        "security": [
          {
            "Auth": [
              "apiTokens|read"
            ]
          }
        ],
        "description": "Get API token by ID",
        "tags": [
          "tokens"
        ],
        "operationId": "getAPIToken"
      },
      "delete": {
        "security": [
          {
            "Auth": [
              "apiTokens|delete"
            ]
          }
        ],
        "description": "Delete API token",
        "tags": [
          "tokens"
        ],
        "operationId": "deleteAPIToken"
      }
    },
    "/tokens/{id}/regenerate": {
      "post": {
        "security": [
          {
            "Auth": [
              "apiTokens|update"
            ]
          }
        ],
        "description": "Regenerate API token",
        "tags": [
          "tokens"
        ],
        "operationId": "regenerateAPIToken",
        "x-axiom-not-suspended": true
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Auth": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
            "scopes": {}
          }
        }
      },
      "Shared": {
        "type": "apiKey",
        "name": "tk",
        "in": "query"
      }
    }
  }
}
