{
  "openapi": "3.0.1",
  "info": {
    "title": "Axiom",
    "description": "A public and stable API for interacting with axiom services",
    "termsOfService": "http://axiom.co/terms",
    "contact": {
      "name": "Axiom support team",
      "url": "https://axiom.co",
      "email": "hello@axiom.co"
    },
    "license": {
      "name": "Apache 2.0",
      "url": "https://www.apache.org/licenses/LICENSE-2.0.html"
    },
    "version": "2.0.0"
  },
  "servers": [
    {
      "url": "https://api.axiom.co/v2/"
    }
  ],
  "security": [
    {
      "Auth": []
    }
  ],
  "paths": {
    "/annotations": {
      "get": {
        "tags": [
          "annotations"
        ],
        "description": "Get annotations",
        "operationId": "getAnnotations",
        "security": [
          {
            "Auth": [
              "annotations|read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "annotations"
        ],
        "description": "Create annotation",
        "operationId": "createAnnotation",
        "security": [
          {
            "Auth": [
              "annotations|create"
            ]
          }
        ]
      }
    },
    "/annotations/{id}": {
      "get": {
        "tags": [
          "annotations"
        ],
        "description": "Get annotation by ID",
        "operationId": "getAnnotation",
        "security": [
          {
            "Auth": [
              "annotations|read"
            ]
          }
        ]
      },
      "put": {
        "tags": [
          "annotations"
        ],
        "description": "Update annotation",
        "operationId": "updateAnnotation",
        "security": [
          {
            "Auth": [
              "annotations|update"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "annotations"
        ],
        "description": "Delete annotation",
        "operationId": "deleteAnnotation",
        "security": [
          {
            "Auth": [
              "annotations|delete"
            ]
          }
        ]
      }
    },
    "/authed": {
      "get": {
        "description": "Get user auth status",
        "operationId": "getAuthed",
        "x-axiom-preview": true
      }
    },
    "/datasets": {
      "get": {
        "tags": [
          "Datasets"
        ],
        "summary": "Get list of datasets",
        "description": "Get list of datasets",
        "operationId": "getDatasets",
        "x-axiom-preview": true
      },
      "post": {
        "tags": [
          "Datasets"
        ],
        "summary": "Create dataset",
        "description": "Create dataset",
        "operationId": "createDataset",
        "security": [
          {
            "Auth": [
              "datasets|create"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/datasets/_apl/delete": {
      "post": {
        "tags": [
          "query"
        ],
        "description": "Delete blocks that have non-zero matches for an APL query.",
        "operationId": "datasetAPLDeletionQuery",
        "security": [
          {
            "Auth": [
              "datasets|update"
            ]
          }
        ],
        "x-axiom-nocompress": true,
        "x-axiom-not-suspended": true
      }
    },
    "/datasets/{id}": {
      "get": {
        "tags": [
          "Datasets"
        ],
        "summary": "Get dataset by ID",
        "description": "Get dataset by ID",
        "operationId": "getDataset",
        "security": [
          {
            "Auth": [
              "datasets|delete"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "put": {
        "tags": [
          "Datasets"
        ],
        "summary": "Update dataset",
        "description": "Update dataset",
        "operationId": "updateDataset",
        "security": [
          {
            "Auth": [
              "datasets|update"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "delete": {
        "tags": [
          "Datasets"
        ],
        "summary": "Delete dataset",
        "description": "Delete dataset",
        "operationId": "deleteDataset",
        "security": [
          {
            "Auth": [
              "datasets|delete"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/datasets/{id}/trim": {
      "post": {
        "tags": [
          "Datasets"
        ],
        "summary": "Trim dataset by duration",
        "description": "Trim dataset",
        "operationId": "trimDataset",
        "security": [
          {
            "Auth": [
              "datasets|update"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/monitors": {
      "get": {
        "tags": [
          "Monitors"
        ],
        "description": "Get monitors",
        "operationId": "getMonitors",
        "security": [
          {
            "Auth": [
              "monitors|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "post": {
        "tags": [
          "Monitors"
        ],
        "description": "Create monitor",
        "operationId": "createMonitor",
        "security": [
          {
            "Auth": [
              "monitors|create"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/monitors/{id}": {
      "get": {
        "tags": [
          "Monitors"
        ],
        "description": "Get monitor by ID",
        "operationId": "getMonitor",
        "security": [
          {
            "Auth": [
              "monitors|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "put": {
        "tags": [
          "Monitors"
        ],
        "description": "Update monitor",
        "operationId": "updateMonitor",
        "security": [
          {
            "Auth": [
              "monitors|update"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "delete": {
        "tags": [
          "Monitors"
        ],
        "description": "Delete monitor",
        "operationId": "deleteMonitor",
        "security": [
          {
            "Auth": [
              "monitors|delete"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/monitors/{id}/history": {
      "get": {
        "tags": [
          "Monitors"
        ],
        "description": "Get monitor history",
        "operationId": "getMonitorHistory",
        "security": [
          {
            "Auth": [
              "monitors|read"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/notifiers": {
      "get": {
        "tags": [
          "Monitors"
        ],
        "description": "Get notifiers",
        "operationId": "getNotifiers",
        "security": [
          {
            "Auth": [
              "notifiers|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "post": {
        "tags": [
          "Monitors"
        ],
        "description": "Create notifier",
        "operationId": "createNotifier",
        "security": [
          {
            "Auth": [
              "notifiers|create"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/notifiers/{id}": {
      "get": {
        "tags": [
          "Monitors"
        ],
        "description": "Get notifier by ID",
        "operationId": "getNotifier",
        "security": [
          {
            "Auth": [
              "notifiers|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "put": {
        "tags": [
          "Monitors"
        ],
        "description": "Update notifier",
        "operationId": "updateNotifier",
        "security": [
          {
            "Auth": [
              "notifiers|update"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "delete": {
        "tags": [
          "Monitors"
        ],
        "description": "Delete notifier",
        "operationId": "deleteNotifier",
        "security": [
          {
            "Auth": [
              "notifiers|delete"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/query": {
      "post": {
        "tags": [
          "query"
        ],
        "summary": "Query datasets using APL",
        "description": "Query data",
        "operationId": "query",
        "security": [
          {
            "Auth": [
              "query/*|read"
            ]
          },
          {
            "Shared": []
          }
        ],
        "x-axiom-not-suspended": true,
        "x-axiom-preview": true
      }
    },
    "/slack/auth": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Authenticate the user",
        "operationId": "handleSlackAuth",
        "security": [
          {
            "Auth": []
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/slack/auth/callback": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Handle OAuth callback from Slack",
        "operationId": "handleOAuthCallback",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/axiomLogin/callback": {
      "get": {
        "tags": [
          "Slack"
        ],
        "description": "Authenticate the user against Axiom",
        "operationId": "handleAxiomLogin",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/events": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Post Slack events",
        "operationId": "postSlackEvent",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/handleSlashCommand": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Redirect user to Slack for authentication",
        "operationId": "handleSlashCommand",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/slack/interactiveEndpoint": {
      "post": {
        "tags": [
          "Slack"
        ],
        "description": "Post Slack interactive endpoint",
        "operationId": "postSlackInteractiveEndpoint",
        "security": [],
        "x-axiom-preview": true
      }
    },
    "/tokens": {
      "get": {
        "tags": [
          "tokens"
        ],
        "description": "Get API tokens",
        "operationId": "getAPITokens",
        "security": [
          {
            "Auth": [
              "apiTokens|read"
            ]
          }
        ]
      },
      "post": {
        "tags": [
          "tokens"
        ],
        "description": "Create API token",
        "operationId": "createAPIToken",
        "security": [
          {
            "Auth": [
              "apiTokens|create"
            ]
          }
        ],
        "x-axiom-not-suspended": true
      }
    },
    "/tokens/{id}": {
      "get": {
        "tags": [
          "tokens"
        ],
        "description": "Get API token by ID",
        "operationId": "getAPIToken",
        "security": [
          {
            "Auth": [
              "apiTokens|read"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "tokens"
        ],
        "description": "Delete API token",
        "operationId": "deleteAPIToken",
        "security": [
          {
            "Auth": [
              "apiTokens|delete"
            ]
          }
        ]
      }
    },
    "/tokens/{id}/regenerate": {
      "post": {
        "tags": [
          "tokens"
        ],
        "description": "Regenerate API token",
        "operationId": "regenerateAPIToken",
        "security": [
          {
            "Auth": [
              "apiTokens|update"
            ]
          }
        ],
        "x-axiom-not-suspended": true
      }
    },
    "/user": {
      "get": {
        "tags": [
          "Users"
        ],
        "description": "Get current user",
        "operationId": "getCurrentUser",
        "x-axiom-preview": true
      }
    },
    "/users": {
      "get": {
        "tags": [
          "Users"
        ],
        "description": "Get users",
        "operationId": "getUsers",
        "security": [
          {
            "Auth": [
              "users|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "post": {
        "tags": [
          "Users"
        ],
        "description": "Create user",
        "operationId": "createUser",
        "security": [
          {
            "Auth": [
              "users|create"
            ]
          }
        ],
        "x-axiom-not-suspended": true,
        "x-axiom-preview": true
      }
    },
    "/users/{id}": {
      "get": {
        "tags": [
          "Users"
        ],
        "description": "Get user by ID",
        "operationId": "getUser",
        "security": [
          {
            "Auth": [
              "users|read"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "put": {
        "tags": [
          "Users"
        ],
        "description": "Update user",
        "operationId": "updateUser",
        "security": [
          {
            "Auth": [
              "users|update"
            ]
          }
        ],
        "x-axiom-preview": true
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "description": "Delete user",
        "operationId": "deleteUser",
        "security": [
          {
            "Auth": [
              "users|delete"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/users/{id}/role": {
      "put": {
        "tags": [
          "Users"
        ],
        "description": "Update user role",
        "operationId": "updateUserRole",
        "security": [
          {
            "Auth": [
              "users|update"
            ]
          }
        ],
        "x-axiom-preview": true
      }
    },
    "/version": {
      "get": {
        "description": "Get version of Axiom instance",
        "operationId": "getVersion",
        "security": [],
        "x-axiom-preview": true
      }
    }
  },
  "components": {
    "securitySchemes": {
      "Auth": {
        "type": "oauth2",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://accounts.google.com/o/oauth2/v2/auth",
            "tokenUrl": "https://www.googleapis.com/oauth2/v4/token",
            "scopes": {}
          }
        }
      },
      "Shared": {
        "type": "apiKey",
        "name": "tk",
        "in": "query"
      }
    }
  },
  "x-original-swagger-version": "2.0"
}